language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - sudo apt update
  - sudo apt install mpich
  - sudo apt-get install libboost-all-dev
  - pip install ".[test]" 
script:
  - pytest
after_success:
  - codecov 
