{% set version = "0.1.0" %}

package:
  name: optimalTAD
  version: {{ version }}

source:
  git_rev:
  git_url:

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
